# Generated by Django 3.2.6 on 2022-08-05 00:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ImageUploderPath.uploadTo, verbose_name='Picture (1:1 ratio is recommended) '),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ImageUploderPath.uploadTo, verbose_name='Picture  ( 1:1 ratio is recommended)'),
        ),
        migrations.AlterField(
            model_name='blogandarticle',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ImageUploderPath.uploadTo, verbose_name='Picture (2.35:1 ratio is recommended)'),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ImageUploderPath.uploadTo, verbose_name='Event banner (2.35:1 ratio is recommended)'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='landing_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ImageUploderPath.uploadTo, verbose_name='landing  picture 1 (210:71 ratio is recommended) '),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='landing_picture_five',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ImageUploderPath.uploadTo, verbose_name='landing  picture 5 (210:71 ratio is recommended) '),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='landing_picture_four',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ImageUploderPath.uploadTo, verbose_name='landing  picture 4 (210:71 ratio is recommended) '),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='landing_picture_three',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ImageUploderPath.uploadTo, verbose_name='landing  picture 3 (210:71 ratio is recommended) '),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='landing_picture_two',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ImageUploderPath.uploadTo, verbose_name='landing  picture 2 (210:71 ratio is recommended) '),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ImageUploderPath.uploadTo, verbose_name='Logo main (1:1  ratio is recommended)'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='logo_2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ImageUploderPath.uploadTo, verbose_name='Logo 2 (1:1  ratio is recommended)'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='logo_3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ImageUploderPath.uploadTo, verbose_name='Logo 3 (1:1  ratio is recommended)'),
        ),
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(height_field='height', upload_to=core.models.ImageUploderPath.uploadTo_withBasefile, verbose_name='Image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='lastnews',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.ImageUploderPath.uploadTo, verbose_name='Picture  ( 16:9 ratio is recommended)'),
        ),
    ]
