"""
Django settings for robotic_club project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from re import DEBUG
# import django_heroku
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATE_DIRS = [os.path.join(BASE_DIR, 'templates')]
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)y#-x2jis2$w7bxto=)!&jog-=69*)=hdn4nkpr)(no5m73pqs'

# SECURITY WARNING: don't run with debug turned`` on in production!
DEBUG=False
if os.getenv("DEBUG")=="on":
    DEBUG=True



ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hitcount',
    'django_summernote',
    'core',
    'members',
    'rest_framework',  # 3d p
    'csvexport',
    'colorfield',
    'blacklist',


]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.cache.UpdateCacheMiddleware', # Per-site cache
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',# Per-site cache
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'blacklist.middleware.BlacklistMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Per-site cache
# CACHE_MIDDLEWARE_ALIAS = 'default'  # which cache alias to use
# CACHE_MIDDLEWARE_SECONDS = '300'    # number of seconds to cache a page for (TTL)
# CACHE_MIDDLEWARE_KEY_PREFIX = ''    # should be used if the cache is shared across multiple sites that use the same Django instance


ROOT_URLCONF = 'robotic_club.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': TEMPLATE_DIRS,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'members.context_processors.get_related_pages_of_members',
                'members.context_processors.get_members_positions',
                'core.context_processors.get_all_semesters',
                'core.context_processors.get_club_info',
                'core.context_processors.get_termsandcondition',
                



            ],
        },
    },
]

WSGI_APPLICATION = 'robotic_club.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

    # 'default':{
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': os.getenv('DB_NAME', 'rac'),
    #     'USER': os.getenv('DB_USER', 'root'),
    #     'PASSWORD': os.getenv('DB_PASSWORD', ''),
    #     'HOST': os.getenv('DB_HOST', '127.0.0.1'),
    #     'PORT': os.getenv('DB_PORT', '3306'),
    #       'OPTIONS': {  
    #         'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"  
    #     }  
    # }  
    
}




# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    BASE_DIR/'static'/'static_dir',
]


STATIC_ROOT = BASE_DIR/'static'/'static_root'
MEDIA_ROOT = BASE_DIR/'media'
if os.getenv('USE_LOCAL_FILE','true')!='true':
    MEDIA_ROOT = '/home/racewuco/racewu.org/media/'
    STATIC_ROOT = '/home/racewuco/racewu.org/static/'




# Activate Django-Heroku.
# django_heroku.settings(locals())


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/admin'

if DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)

# 3rd party summernor module for more
# https://github.com/summernote/django-summernote
SUMMERNOTE_THEME = 'bs4'
SUMMERNOTE_CONFIG = {
    'summernote': {
    # 'fontNames': [

    # 
    # ],
    # 'fontNamesIgnoreCheck': [''],
    'fontNames': [   
                    'inherit',           
                    'sans-serif','arial black',
                    'Comic Sans Ms','courier new','halvetica',
                    'IMPACT','time new roman','VERDANA',
                    'Roboto Light', 'Roboto Regular', 'Roboto Bold'],

    'fontNamesIgnoreCheck': [   
                    'inherit',           
                    'sans-serif','arial black',
                    'Comic Sans Ms','courier new','halvetica',
                    'IMPACT','time new roman','VERDANA',
                    'Roboto Light', 'Roboto Regular', 'Roboto Bold'
                    
                    ],
    }
}

# mail config 

EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER=os.getenv('EMAIL_HOST_USER', 'invalid@email')
EMAIL_HOST_PASSWORD=os.getenv('EMAIL_HOST_USER', 'pass')



# blacklist
# https://github.com/vsemionov/django-blacklist

BLACKLIST_TEMPLATE='blacklist.html'
CSRF_FAILURE_VIEW = 'core.views.csrf_failure'
